{
    "name": "TVProgram",
    "version": "1.1.7",
    "icon": "fas fa-tv",
    "category": "information",
    "author": "philipp2310",
    "maintainers": [
        "Psychokiller1888",
        "maxbachmann"
    ],
    "desc": "What's on TV today?",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [
        "xmltodict"
    ],
    "conditions": {
        "lang": [
            "de"
        ],
        "online": true
    }
}